sync:
    port: 3015
    log_peer_connection_count_interval: 6000000

keys:
    dir: keys
    peer_password: "secret"

http:
    external:
        port: 3013
    internal:
        port: 3113

websocket:
    channel:
        port: 3014

mining:
    autostart: false
    beneficiary: "ak_2Dri7n9Bm2FgdN5ZFXzDn1ZAXUMox6roEWTfU1rCQ842pTdWiK"

chain:
    persist: true
    garbage_collection:
        enabled: false
        interval: 3
        history: 500

fork_management:
    network_id: ae_uat